version: '3.8'

services:
  app:
    build: .
    container_name: mails-docker-app
    volumes:
      - ./data:/app/data
    environment:
      - TEMPMAILG_URL=https://tempmailg.com/es
      - DB_PATH=/app/data/emails.db
      - CHROME_DRIVER_PATH=/usr/local/bin/chromedriver
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  data:
